[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn main_app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 